version: '3'
services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        hostname: "rabbit1"
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: 'bitnami/redis:5.0'
        container_name: redis
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local